export const redactPaths = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["x-api-key"]',
  'req.headers["x-auth-token"]',
  '*.password',
  '*.confirmPassword',
  '*.oldPassword',
  '*.newPassword',
  '*.token',
  '*.accessToken',
  '*.refreshToken',
  '*.secret',
  '*.apiKey',
  '*.api_key',
  '*.privateKey',
  '*.creditCard',
  '*.cardNumber',
  '*.cvv',
  '*.ssn',
  '*.OPENAI_API_KEY',
  '*.S3_SECRET_ACCESS_KEY',
  '*.POSTGRES_PASSWORD',
  '*.JWT_SECRET',
  '*.JWT_PRIVATE_KEY',
  'req.body.password',
  'req.body.token',
  'req.body.secret',
  'res.body.token',
  'res.body.accessToken',
  'res.body.refreshToken',
];

export const redactCensor = '[REDACTED]';
