import { SecretValue } from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

import { names, SECRET_PLACEHOLDER } from './config.ts';

import type { SecretKey } from './config.ts';

/**
 * Secrets Manager entries, plain strings. The DB password is generated here; the JWT pair and the OpenAI key
 * cannot be generated by CloudFormation, so they start as a placeholder and scripts/set-secrets.ts fills them.
 */
export class Secrets extends Construct {
  readonly dbPassword: secretsmanager.Secret;
  readonly all: secretsmanager.Secret[];

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.dbPassword = new secretsmanager.Secret(this, 'DbPassword', {
      secretName: names.secret('POSTGRES_PASSWORD'),
      generateSecretString: { passwordLength: 32, excludePunctuation: true },
    });

    const placeholder = (logicalId: string, key: SecretKey, description: string) =>
      new secretsmanager.Secret(this, logicalId, {
        secretName: names.secret(key),
        description,
        secretStringValue: SecretValue.unsafePlainText(SECRET_PLACEHOLDER),
      });

    this.all = [
      this.dbPassword,
      placeholder('JwtPrivateKey', 'JWT_PRIVATE_KEY', 'RS256 private key, base64(PEM): only auth'),
      placeholder('JwtPublicKey', 'JWT_PUBLIC_KEY', 'RS256 public key, base64(PEM): every service'),
      placeholder('OpenAiKey', 'OPENAI_API_KEY', 'Set with scripts/set-secrets.ts'),
    ];
  }
}
