/**
 * GENERATED by `pnpm --filter billing contracts:generate` (nestjs-trpc). Do not edit.
 */
/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from '@trpc/server';

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { pingInputSchema, pingOutputSchema } from '../common';
import { invoicesGetByOrderInputSchema, invoicesGetByOrderOutputSchema } from './schemas';

const appRouter = t.router({
  health: t.router({
    ping: publicProcedure
      .input(pingInputSchema)
      .output(pingOutputSchema)
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
  invoices: t.router({
    getByOrder: publicProcedure
      .input(invoicesGetByOrderInputSchema)
      .output(invoicesGetByOrderOutputSchema)
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
});

export type AppRouter = typeof appRouter;
